---
- group: gid=10000 name=powerdns
- user: name="{{ item.name }}" comment="{{ item.comment }}" uid={{ item.uid }}  group="{{ item.group | default("powerdns") }}" groups="{{ item.groups | default("adm,sudo") }}" password="{{ item.password }}" state="{{ item.state | default("absent")}}" shell="{{ item.shell | default("/bin/bash") }}"
  with_items: users
- authorized_key: user="{{ item.0.name }}" key="{{ lookup('file', item.1) }}"
  with_subelements:
    - users
    - authorized_key
